// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using backend.Data;

#nullable disable

namespace backend.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251225095843_MapGraph")]
    partial class MapGraph
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("backend.Models.Map", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Maps");
                });

            modelBuilder.Entity("backend.Models.MapPoint", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<double>("Offset")
                        .HasColumnType("double precision");

                    b.Property<int>("PathId")
                        .HasColumnType("integer");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("PathId");

                    b.ToTable("MapPoints");
                });

            modelBuilder.Entity("backend.Models.Node", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,0)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.ToTable("Nodes");
                });

            modelBuilder.Entity("backend.Models.Path", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("EndNodeId")
                        .HasColumnType("integer");

                    b.Property<double>("Length")
                        .HasColumnType("double precision");

                    b.Property<LineString>("Location")
                        .HasColumnType("geometry(LineString,0)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<int>("StartNodeId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("TwoWay")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("EndNodeId");

                    b.HasIndex("MapId");

                    b.HasIndex("StartNodeId");

                    b.ToTable("Paths");
                });

            modelBuilder.Entity("backend.Models.Qr", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point,0)");

                    b.Property<int>("MapId")
                        .HasColumnType("integer");

                    b.Property<double>("OffsetStart")
                        .HasColumnType("double precision");

                    b.Property<int>("PathId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MapId");

                    b.HasIndex("PathId");

                    b.ToTable("Qrs");
                });

            modelBuilder.Entity("backend.Models.Robot", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<double>("Battery")
                        .HasColumnType("double precision");

                    b.Property<bool>("Connected")
                        .HasColumnType("boolean");

                    b.Property<Point>("Geom")
                        .HasColumnType("geometry(Point,0)");

                    b.Property<string>("Ip")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime?>("LastActive")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("X")
                        .HasColumnType("double precision");

                    b.Property<double>("Y")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("Ip");

                    b.ToTable("Robots");
                });

            modelBuilder.Entity("backend.Models.MapPoint", b =>
                {
                    b.HasOne("backend.Models.Map", "Map")
                        .WithMany("Points")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Path", "Path")
                        .WithMany("Points")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("backend.Models.Node", b =>
                {
                    b.HasOne("backend.Models.Map", "Map")
                        .WithMany("Nodes")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");
                });

            modelBuilder.Entity("backend.Models.Path", b =>
                {
                    b.HasOne("backend.Models.Node", "EndNode")
                        .WithMany("PathsEnding")
                        .HasForeignKey("EndNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("backend.Models.Map", "Map")
                        .WithMany("Paths")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Node", "StartNode")
                        .WithMany("PathsStarting")
                        .HasForeignKey("StartNodeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EndNode");

                    b.Navigation("Map");

                    b.Navigation("StartNode");
                });

            modelBuilder.Entity("backend.Models.Qr", b =>
                {
                    b.HasOne("backend.Models.Map", "Map")
                        .WithMany("Qrs")
                        .HasForeignKey("MapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("backend.Models.Path", "Path")
                        .WithMany("Qrs")
                        .HasForeignKey("PathId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Map");

                    b.Navigation("Path");
                });

            modelBuilder.Entity("backend.Models.Map", b =>
                {
                    b.Navigation("Nodes");

                    b.Navigation("Paths");

                    b.Navigation("Points");

                    b.Navigation("Qrs");
                });

            modelBuilder.Entity("backend.Models.Node", b =>
                {
                    b.Navigation("PathsEnding");

                    b.Navigation("PathsStarting");
                });

            modelBuilder.Entity("backend.Models.Path", b =>
                {
                    b.Navigation("Points");

                    b.Navigation("Qrs");
                });
#pragma warning restore 612, 618
        }
    }
}
