// <auto-generated />
using System;
using BackendV3.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backendV3.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260121021619_MapsVersionedEntityKeys")]
    partial class MapsVersionedEntityKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BackendV3.Modules.Auth.Model.RevokedToken", b =>
                {
                    b.Property<Guid>("RevocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Jti")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("RevokedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("RevocationId");

                    b.HasIndex("Jti")
                        .IsUnique();

                    b.ToTable("revoked_tokens", "auth");
                });

            modelBuilder.Entity("BackendV3.Modules.Auth.Model.Role", b =>
                {
                    b.Property<Guid>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("RoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("roles", "auth");
                });

            modelBuilder.Entity("BackendV3.Modules.Auth.Model.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsDisabled")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("users", "auth");
                });

            modelBuilder.Entity("BackendV3.Modules.Auth.Model.UserRole", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("user_roles", "auth");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.Map", b =>
                {
                    b.Property<Guid>("MapId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivePublishedMapVersionId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MapId");

                    b.HasIndex("ActivePublishedMapVersionId");

                    b.HasIndex("ArchivedAt");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("maps", "maps");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.MapNode", b =>
                {
                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("NodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaintenance")
                        .HasColumnType("boolean");

                    b.Property<double?>("JunctionSpeedLimit")
                        .HasColumnType("double precision");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 0)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.HasKey("MapVersionId", "NodeId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MapVersionId");

                    b.ToTable("map_nodes", "maps");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.MapPath", b =>
                {
                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PathId")
                        .HasColumnType("uuid");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("FromNodeId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsMaintenance")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRestPath")
                        .HasColumnType("boolean");

                    b.Property<double>("LengthMeters")
                        .HasColumnType("double precision");

                    b.Property<LineString>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(LineString, 0)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<int?>("RestCapacity")
                        .HasColumnType("integer");

                    b.Property<string>("RestDwellPolicy")
                        .HasColumnType("text");

                    b.Property<double?>("SpeedLimit")
                        .HasColumnType("double precision");

                    b.Property<Guid>("ToNodeId")
                        .HasColumnType("uuid");

                    b.HasKey("MapVersionId", "PathId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MapVersionId");

                    b.ToTable("map_paths", "maps");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.MapPoint", b =>
                {
                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PointId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AttachedNodeId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Point>("Location")
                        .IsRequired()
                        .HasColumnType("geometry(Point, 0)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MapVersionId", "PointId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MapVersionId");

                    b.ToTable("map_points", "maps");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.MapVersion", b =>
                {
                    b.Property<Guid>("MapVersionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ChangeSummary")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DerivedFromMapVersionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .HasColumnType("text");

                    b.Property<Guid>("MapId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("PublishedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.HasKey("MapVersionId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("DerivedFromMapVersionId");

                    b.HasIndex("MapId")
                        .IsUnique()
                        .HasFilter("\"Status\" = 'PUBLISHED'");

                    b.HasIndex("PublishedAt");

                    b.HasIndex("PublishedBy");

                    b.HasIndex("MapId", "Status");

                    b.HasIndex("MapId", "Version")
                        .IsUnique();

                    b.ToTable("map_versions", "maps");
                });

            modelBuilder.Entity("BackendV3.Modules.Maps.Model.QrAnchor", b =>
                {
                    b.Property<Guid>("MapVersionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QrId")
                        .HasColumnType("uuid");

                    b.Property<double>("DistanceAlongPath")
                        .HasColumnType("double precision");

                    b.Property<Point>("Location")
                        .HasColumnType("geometry(Point, 0)");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("text");

                    b.Property<Guid>("PathId")
                        .HasColumnType("uuid");

                    b.Property<string>("QrCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("MapVersionId", "QrId");

                    b.HasIndex("Location");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("Location"), "gist");

                    b.HasIndex("MapVersionId");

                    b.HasIndex("PathId");

                    b.ToTable("qr_anchors", "maps");
                });
#pragma warning restore 612, 618
        }
    }
}
